---
#This Code is for 16.1 and above as the build contains a fix for guest customization to work correctly.
#Deploy OVA
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - roles/F5-Roles/date_time

# Build F5 VMs
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - /git/vars/vmc/vault.yml
  roles:
    - roles/AWS-VPC/create_dyn_group_f5_vpc

- hosts: dynamic_aws_f5
  connection: local
  gather_facts: false
  vars_files:
    - /git/vars/vmc/vault.yml
    - /git/vars/vmc/deployment.yml
  roles:
    - roles/AWS-VPC/setup_variables
    - roles/F5-Roles/install_as3
    - roles/F5-Roles/install_do
    - roles/F5-Roles/cleanup_downloads
    - roles/F5-Roles/restart_services_check
    - roles/F5-Roles/as3_configure_ec2

# End-Time
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - roles/F5-Roles/date_time
