---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - roles/F5-Roles/date_time

# Build F5 VMs
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - /git/vars/vmc/vault.yml
    - /git/vars/vmc/deployment.yml
  roles:
    - roles/vSphere-Roles/create_dyn_group_f5_vms

# Build F5 VMs
- hosts: dynamic_f5_vms
  connection: local
  gather_facts: true
  vars_files:
    - /git/vars/vmc/vault.yml
    - /git/vars/vmc/deployment.yml
  roles:
    - roles/F5-Roles/f5_backup_data

- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - roles/F5-Roles/date_time