---
# tasks install Declaritive Onboarding Latest

  - name: Get latest AS3 RPM
    ansible.builtin.shell: curl -s {{as3_uri}} | grep -E rpm |grep -E browser_download_url | head -1 | cut -d "\"" -f 4
    register: as3_output
    delegate_to: localhost

  - debug:
      var: as3_output.stdout_lines[0]

  - ansible.builtin.set_fact:
      as3_download: "{{as3_output.stdout_lines[0]}}"
    delegate_to: localhost

  - name: Grab AS3 RPM from github
    ansible.builtin.get_url:
      url: "{{as3_download}}?raw=true"
      dest: "~/"
      validate_certs: false
    delegate_to: localhost

  - name: Grab the AS3 version from the home directory
    ansible.builtin.shell: ls -Art ~/*.rpm | tail -n 1 | rev | cut -d/ -f 1 | rev
    register: ls_output

  - ansible.builtin.set_fact:
      as3_rpm: "{{ls_output.stdout}}"
    delegate_to: localhost

  - name: Install AS3
    f5networks.f5_modules.bigip_lx_package:
      package: "~/{{as3_rpm}}"
      provider: "{{provider}}"
    register: install_as3
    delegate_to: localhost
    retries: 10
    until: install_as3 is not failed