---
# tasks file for Create-Resource-Pool

  - name: Get the existing resource pools
    vmware.vmware_rest.vcenter_resourcepool_info:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_username: "{{ vcenter_username }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    register: resource_pools

  - debug:
      var: resource_pools

  - debug:
      var: item
    with_items: resource_pools.value      

  - name: Create an Ad hoc resource pool
    vmware.vmware_rest.vcenter_resourcepool:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_username: "{{ vcenter_username }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{resource_pool_name}}"
      parent: '{{ item.resource_pool }}'
    register: my_resource_pool
    when: item.resource_pool.name == "Resources"
    with_items: resource_pools.value

  # - name: Add Resource Pool to vCenter
  #   vmware.vmware_rest.vcenter_resourcepool:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     validate_certs: "{{ vcenter_validate_certs }}"
  #     datacenter: "{{ datacenter_name }}"
  #     cluster: "{{ cluster_name }}"
  #     resource_pool: "{{resource_pool_name}}"
  #     state: present
  #   delegate_to: localhost


